# Generated by Django 5.0 on 2023-12-07 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=250)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('description', models.CharField(max_length=3000)),
                ('points', models.IntegerField(default=0)),
                ('max_players', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Army',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('points', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=3000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wargameapi.category')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=150)),
                ('event_location', models.CharField(max_length=150)),
                ('event_time', models.DateTimeField(default=None)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wargameapi.game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wargameapi.system'),
        ),
        migrations.CreateModel(
            name='WargameUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=3000)),
                ('profile_image_url', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wargameapi.wargameuser'),
        ),
        migrations.CreateModel(
            name='EventGamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=None)),
                ('army', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wargameapi.army')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wargameapi.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wargameapi.wargameuser')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wargameapi.wargameuser'),
        ),
        migrations.AddField(
            model_name='army',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wargameapi.wargameuser'),
        ),
    ]
