# Generated by Django 5.0 on 2023-12-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wargameapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wargameuser',
            name='wargame_username',
            field=models.CharField(default='default_username', max_length=65),
        ),
    ]
