# Generated by Django 4.2.7 on 2023-12-15 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wargameapi', '0002_wargameuser_wargame_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgamer',
            name='army',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wargameapi.army'),
        ),
        migrations.AlterField(
            model_name='eventgamer',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
